#!/bin/sh
value=`cat ../secret`
git pull https://mungert69:$value@github.com/Mungert69/FreeNetworkMonitorBlog
npm install 
npm run export
docker compose -f docker-compose-local.yml build
docker push mungert/networkmonitorblog-local:0.9.0
