#!/bin/sh
value=`cat ../secret`
git pull https://mungert69:$value@github.com/Mungert69/FreeNetworkMonitorBlog
npm install 
mkdir -p ./out/images
mkdir -p ./out/blogpics
cp ./public/runConfig-dev.json ./public/runConfig.json
npm run export
docker compose -f docker-compose-local.yml build
docker push mungert/networkmonitorblog-local:0.9.0
