#!/bin/sh
set -eu

npm install 
cp ./public/runConfig-live.js ./public/runConfig.js
cp ./public/runConfig-live.json ./public/runConfig.json
npm run export
mkdir -p ./out/images
mkdir -p ./out/blogpics
docker buildx inspect multiarch-builder >/dev/null 2>&1 || docker buildx create --name multiarch-builder --use
docker buildx use multiarch-builder
docker buildx inspect --bootstrap
docker buildx build \
  --platform linux/amd64,linux/arm64 \
  --file ./Dockerfile \
  --tag mungert/networkmonitorblog:1.3.0 \
  --push \
  .
