#!/bin/bash

# Set the root directory where the folders are located
root_directory="./blogpics"

# Find all folders within the root directory
find "$root_directory" -type d | while read -r folder; do

  # Find all image files within each folder
  find "$folder" -type f \( -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.png" \) | while read -r image; do

    # Get the filename
    filename=$(basename "$image")


    # Set the output filename with webp extension
    webp_filename="${filename%.*}.webp"

    # Convert and resize image to WebP format using ImageMagick
    convert "$image" -resize x300 "$folder/$webp_filename"

    echo "Converted: $folder/$resized_filename -> $folder/$webp_filename"
  done
done

